# Generated by Django 5.0.3 on 2024-04-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_email1_orders_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='email5',
        ),
    ]
